name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-scripts --no-progress

      - name: Configure environment file
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root

      - name: Check existing tables
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "USE test_db; SHOW TABLES;"

      - name: Run Laravel migrations
        run: php artisan migrate --env=testing
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root

      - name: Run Laravel tests
        run: php artisan test --env=testing
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Print environment variables for debugging
        run: |
          echo "FTP_SERVER: $FTP_SERVER"
          echo "FTP_USERNAME: $FTP_USERNAME"
        env:
          FTP_SERVER: ftp.siforta.my.id
          FTP_USERNAME: sifortam2@siforta.my.id

      - name: Test FTP Connection
        run: |
          nc -zv ftp.siforta.my.id 21

      - name: Create directories on server using lftp (debugging)
        run: |
          set -x
          time lftp -d -e "
          set ftp:ssl-allow no;
          open ftp.siforta.my.id;
          user sifortam2@siforta.my.id Siforta12345#;
          mkdir -p /home/sifortam/siforta.my.id/siforta;
          bye
          "
        env:
          FTP_SERVER: ftp.siforta.my.id
          FTP_USERNAME: sifortam2@siforta.my.id
          FTP_PASSWORD: Siforta12345#

      - name: Create directories on server using curl (alternative)
        run: |
          set -x
          time curl -u siforta@siforta.my.id:Siforta12345# ftp://ftp.siforta.my.id/home/sifortam/siforta.my.id/siforta/ --create-dirs
        env:
          FTP_SERVER: ftp.siforta.my.id
          FTP_USERNAME: sifortam2@siforta.my.id
          FTP_PASSWORD: Siforta12345#

      - name: Create siforta directory locally
        run: mkdir -p ./siforta

      - name: List current directory
        run: ls -la

      - name: List siforta directory
        run: ls -la ./siforta

      - name: Deploy to server via FTP (debugging)
        run: |
          set -x
          time lftp -d -e "
          set ftp:ssl-allow no;
          open ftp.siforta.my.id;
          user sifortam2@siforta.my.id Siforta12345#;
          mirror -R /home/sifortam/siforta.my.id/sifortam2;
          bye
          "
        env:
          FTP_SERVER: ftp.siforta.my.id
          FTP_USERNAME: siforta@siforta.my.id
          FTP_PASSWORD: Siforta12345#
