name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-scripts --no-progress

      - name: Configure environment file
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1       # Placeholder: Ganti dengan host database Anda
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root

      - name: Check existing tables
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "USE test_db; SHOW TABLES;"
      - name: Run Laravel migrations
        run: php artisan migrate --env=testing
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1       # Placeholder: Ganti dengan host database Anda
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root

      - name: Run Laravel tests
        run: php artisan test --env=testing
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1       # Placeholder: Ganti dengan host database Anda
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-scripts --no-progress

      - name: Deploy to server via SSH
        env:
          FTP_SERVER: ${{ secrets.ftp.siforta.my.id }}
          FTP_USERNAME: ${{ secrets.sifortam }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            cd /path/to/your/project      # Placeholder: Ganti dengan path sebenarnya ke direktori proyek di server
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
          EOF
